### ISSUE TITLE
iPad 不能玩，未报错但是球不动

### ISSUE THREAD

**Issue by imluisfigo** [knightyun/maze-game#1]
无法识别重力传感器？

**Comment by knightyun** [comment]
> 无法识别重力传感器？

有可能，程序目前只是简单的设置 devicemotion 事件的监听，后面有时间会解决下适配问题。

**Comment by knightyun** [comment]
已完善传感器检测功能，并作相应提示 master@157f8f6

**Comment by knightyun** [comment]
@imluisfigo 已完善传感器检测功能，并作相应提示<https://github.com/knightyun/maze-game/commit/157f8f6d308cd8e59c50743a391853d0bf2a835a>
